//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
// 
#pragma warning disable 1591

namespace is2WebApplication.is2init {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://Walkthrough/XmlWebServices/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Set_tanmatsuOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upd_tanmatsuOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upd_riyouOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_tanmatsu2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_riyouOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_seikyuOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_jyotaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_syukabiOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_bumonOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_messageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_seigyoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ins_seigyoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upd_seigyoOperationCompleted;
        
        private System.Threading.SendOrPostCallback login2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Upd_tanmatuOperationCompleted;
        
        private System.Threading.SendOrPostCallback wakeupDBOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost/is2/is2init/Service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Set_tanmatsuCompletedEventHandler Set_tanmatsuCompleted;
        
        /// <remarks/>
        public event Upd_tanmatsuCompletedEventHandler Upd_tanmatsuCompleted;
        
        /// <remarks/>
        public event Upd_riyouCompletedEventHandler Upd_riyouCompleted;
        
        /// <remarks/>
        public event Get_tanmatsu2CompletedEventHandler Get_tanmatsu2Completed;
        
        /// <remarks/>
        public event Get_riyouCompletedEventHandler Get_riyouCompleted;
        
        /// <remarks/>
        public event Get_seikyuCompletedEventHandler Get_seikyuCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event Get_jyotaiCompletedEventHandler Get_jyotaiCompleted;
        
        /// <remarks/>
        public event Get_syukabiCompletedEventHandler Get_syukabiCompleted;
        
        /// <remarks/>
        public event Get_bumonCompletedEventHandler Get_bumonCompleted;
        
        /// <remarks/>
        public event Get_messageCompletedEventHandler Get_messageCompleted;
        
        /// <remarks/>
        public event Get_seigyoCompletedEventHandler Get_seigyoCompleted;
        
        /// <remarks/>
        public event Ins_seigyoCompletedEventHandler Ins_seigyoCompleted;
        
        /// <remarks/>
        public event Upd_seigyoCompletedEventHandler Upd_seigyoCompleted;
        
        /// <remarks/>
        public event login2CompletedEventHandler login2Completed;
        
        /// <remarks/>
        public event Upd_tanmatuCompletedEventHandler Upd_tanmatuCompleted;
        
        /// <remarks/>
        public event wakeupDBCompletedEventHandler wakeupDBCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Set_tanmatsu", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Set_tanmatsu(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Set_tanmatsu", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSet_tanmatsu(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Set_tanmatsu", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndSet_tanmatsu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Set_tanmatsuAsync(string[] sUser, string[] sKey) {
            this.Set_tanmatsuAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Set_tanmatsuAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Set_tanmatsuOperationCompleted == null)) {
                this.Set_tanmatsuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_tanmatsuOperationCompleted);
            }
            this.InvokeAsync("Set_tanmatsu", new object[] {
                        sUser,
                        sKey}, this.Set_tanmatsuOperationCompleted, userState);
        }
        
        private void OnSet_tanmatsuOperationCompleted(object arg) {
            if ((this.Set_tanmatsuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_tanmatsuCompleted(this, new Set_tanmatsuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_tanmatsu", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upd_tanmatsu(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Upd_tanmatsu", new object[] {
                        sUser,
                        sKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_tanmatsu(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_tanmatsu", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpd_tanmatsu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upd_tanmatsuAsync(string[] sUser, string[] sKey) {
            this.Upd_tanmatsuAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Upd_tanmatsuAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Upd_tanmatsuOperationCompleted == null)) {
                this.Upd_tanmatsuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpd_tanmatsuOperationCompleted);
            }
            this.InvokeAsync("Upd_tanmatsu", new object[] {
                        sUser,
                        sKey}, this.Upd_tanmatsuOperationCompleted, userState);
        }
        
        private void OnUpd_tanmatsuOperationCompleted(object arg) {
            if ((this.Upd_tanmatsuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upd_tanmatsuCompleted(this, new Upd_tanmatsuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_riyou", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upd_riyou(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Upd_riyou", new object[] {
                        sUser,
                        sKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_riyou(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_riyou", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpd_riyou(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upd_riyouAsync(string[] sUser, string[] sKey) {
            this.Upd_riyouAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Upd_riyouAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Upd_riyouOperationCompleted == null)) {
                this.Upd_riyouOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpd_riyouOperationCompleted);
            }
            this.InvokeAsync("Upd_riyou", new object[] {
                        sUser,
                        sKey}, this.Upd_riyouOperationCompleted, userState);
        }
        
        private void OnUpd_riyouOperationCompleted(object arg) {
            if ((this.Upd_riyouCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upd_riyouCompleted(this, new Upd_riyouCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_tanmatsu2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_tanmatsu2(string[] sUser, string sKey1) {
            object[] results = this.Invoke("Get_tanmatsu2", new object[] {
                        sUser,
                        sKey1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_tanmatsu2(string[] sUser, string sKey1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_tanmatsu2", new object[] {
                        sUser,
                        sKey1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_tanmatsu2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_tanmatsu2Async(string[] sUser, string sKey1) {
            this.Get_tanmatsu2Async(sUser, sKey1, null);
        }
        
        /// <remarks/>
        public void Get_tanmatsu2Async(string[] sUser, string sKey1, object userState) {
            if ((this.Get_tanmatsu2OperationCompleted == null)) {
                this.Get_tanmatsu2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_tanmatsu2OperationCompleted);
            }
            this.InvokeAsync("Get_tanmatsu2", new object[] {
                        sUser,
                        sKey1}, this.Get_tanmatsu2OperationCompleted, userState);
        }
        
        private void OnGet_tanmatsu2OperationCompleted(object arg) {
            if ((this.Get_tanmatsu2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_tanmatsu2Completed(this, new Get_tanmatsu2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_riyou", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_riyou(string[] sUser, string sKey1, string sKey2) {
            object[] results = this.Invoke("Get_riyou", new object[] {
                        sUser,
                        sKey1,
                        sKey2});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_riyou(string[] sUser, string sKey1, string sKey2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_riyou", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_riyou(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_riyouAsync(string[] sUser, string sKey1, string sKey2) {
            this.Get_riyouAsync(sUser, sKey1, sKey2, null);
        }
        
        /// <remarks/>
        public void Get_riyouAsync(string[] sUser, string sKey1, string sKey2, object userState) {
            if ((this.Get_riyouOperationCompleted == null)) {
                this.Get_riyouOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_riyouOperationCompleted);
            }
            this.InvokeAsync("Get_riyou", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, this.Get_riyouOperationCompleted, userState);
        }
        
        private void OnGet_riyouOperationCompleted(object arg) {
            if ((this.Get_riyouCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_riyouCompleted(this, new Get_riyouCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_seikyu", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_seikyu(string[] sUser, string sKey1, string sKey2) {
            object[] results = this.Invoke("Get_seikyu", new object[] {
                        sUser,
                        sKey1,
                        sKey2});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_seikyu(string[] sUser, string sKey1, string sKey2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_seikyu", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_seikyu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_seikyuAsync(string[] sUser, string sKey1, string sKey2) {
            this.Get_seikyuAsync(sUser, sKey1, sKey2, null);
        }
        
        /// <remarks/>
        public void Get_seikyuAsync(string[] sUser, string sKey1, string sKey2, object userState) {
            if ((this.Get_seikyuOperationCompleted == null)) {
                this.Get_seikyuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_seikyuOperationCompleted);
            }
            this.InvokeAsync("Get_seikyu", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, this.Get_seikyuOperationCompleted, userState);
        }
        
        private void OnGet_seikyuOperationCompleted(object arg) {
            if ((this.Get_seikyuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_seikyuCompleted(this, new Get_seikyuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/login", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] login(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("login", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string[] sUser, string[] sKey) {
            this.loginAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void loginAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        sUser,
                        sKey}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_jyotai", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_jyotai(string[] sUser) {
            object[] results = this.Invoke("Get_jyotai", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_jyotai(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_jyotai", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_jyotai(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_jyotaiAsync(string[] sUser) {
            this.Get_jyotaiAsync(sUser, null);
        }
        
        /// <remarks/>
        public void Get_jyotaiAsync(string[] sUser, object userState) {
            if ((this.Get_jyotaiOperationCompleted == null)) {
                this.Get_jyotaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_jyotaiOperationCompleted);
            }
            this.InvokeAsync("Get_jyotai", new object[] {
                        sUser}, this.Get_jyotaiOperationCompleted, userState);
        }
        
        private void OnGet_jyotaiOperationCompleted(object arg) {
            if ((this.Get_jyotaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_jyotaiCompleted(this, new Get_jyotaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syukabi", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_syukabi(string[] sUser, string sKey1, string sKey2) {
            object[] results = this.Invoke("Get_syukabi", new object[] {
                        sUser,
                        sKey1,
                        sKey2});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_syukabi(string[] sUser, string sKey1, string sKey2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_syukabi", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_syukabi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_syukabiAsync(string[] sUser, string sKey1, string sKey2) {
            this.Get_syukabiAsync(sUser, sKey1, sKey2, null);
        }
        
        /// <remarks/>
        public void Get_syukabiAsync(string[] sUser, string sKey1, string sKey2, object userState) {
            if ((this.Get_syukabiOperationCompleted == null)) {
                this.Get_syukabiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_syukabiOperationCompleted);
            }
            this.InvokeAsync("Get_syukabi", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, this.Get_syukabiOperationCompleted, userState);
        }
        
        private void OnGet_syukabiOperationCompleted(object arg) {
            if ((this.Get_syukabiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_syukabiCompleted(this, new Get_syukabiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_bumon", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_bumon(string[] sUser, string sKey1) {
            object[] results = this.Invoke("Get_bumon", new object[] {
                        sUser,
                        sKey1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_bumon(string[] sUser, string sKey1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_bumon", new object[] {
                        sUser,
                        sKey1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_bumon(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_bumonAsync(string[] sUser, string sKey1) {
            this.Get_bumonAsync(sUser, sKey1, null);
        }
        
        /// <remarks/>
        public void Get_bumonAsync(string[] sUser, string sKey1, object userState) {
            if ((this.Get_bumonOperationCompleted == null)) {
                this.Get_bumonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_bumonOperationCompleted);
            }
            this.InvokeAsync("Get_bumon", new object[] {
                        sUser,
                        sKey1}, this.Get_bumonOperationCompleted, userState);
        }
        
        private void OnGet_bumonOperationCompleted(object arg) {
            if ((this.Get_bumonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_bumonCompleted(this, new Get_bumonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_message", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_message(string[] sUser, string sKey1, string sKey2) {
            object[] results = this.Invoke("Get_message", new object[] {
                        sUser,
                        sKey1,
                        sKey2});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_message(string[] sUser, string sKey1, string sKey2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_message", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_message(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_messageAsync(string[] sUser, string sKey1, string sKey2) {
            this.Get_messageAsync(sUser, sKey1, sKey2, null);
        }
        
        /// <remarks/>
        public void Get_messageAsync(string[] sUser, string sKey1, string sKey2, object userState) {
            if ((this.Get_messageOperationCompleted == null)) {
                this.Get_messageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_messageOperationCompleted);
            }
            this.InvokeAsync("Get_message", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, this.Get_messageOperationCompleted, userState);
        }
        
        private void OnGet_messageOperationCompleted(object arg) {
            if ((this.Get_messageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_messageCompleted(this, new Get_messageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_seigyo", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_seigyo(string[] sUser, string sKey1, string sKey2) {
            object[] results = this.Invoke("Get_seigyo", new object[] {
                        sUser,
                        sKey1,
                        sKey2});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_seigyo(string[] sUser, string sKey1, string sKey2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_seigyo", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_seigyo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_seigyoAsync(string[] sUser, string sKey1, string sKey2) {
            this.Get_seigyoAsync(sUser, sKey1, sKey2, null);
        }
        
        /// <remarks/>
        public void Get_seigyoAsync(string[] sUser, string sKey1, string sKey2, object userState) {
            if ((this.Get_seigyoOperationCompleted == null)) {
                this.Get_seigyoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_seigyoOperationCompleted);
            }
            this.InvokeAsync("Get_seigyo", new object[] {
                        sUser,
                        sKey1,
                        sKey2}, this.Get_seigyoOperationCompleted, userState);
        }
        
        private void OnGet_seigyoOperationCompleted(object arg) {
            if ((this.Get_seigyoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_seigyoCompleted(this, new Get_seigyoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Ins_seigyo", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ins_seigyo(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Ins_seigyo", new object[] {
                        sUser,
                        sKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIns_seigyo(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ins_seigyo", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndIns_seigyo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Ins_seigyoAsync(string[] sUser, string[] sKey) {
            this.Ins_seigyoAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Ins_seigyoAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Ins_seigyoOperationCompleted == null)) {
                this.Ins_seigyoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIns_seigyoOperationCompleted);
            }
            this.InvokeAsync("Ins_seigyo", new object[] {
                        sUser,
                        sKey}, this.Ins_seigyoOperationCompleted, userState);
        }
        
        private void OnIns_seigyoOperationCompleted(object arg) {
            if ((this.Ins_seigyoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ins_seigyoCompleted(this, new Ins_seigyoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_seigyo", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upd_seigyo(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Upd_seigyo", new object[] {
                        sUser,
                        sKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_seigyo(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_seigyo", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndUpd_seigyo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upd_seigyoAsync(string[] sUser, string[] sKey) {
            this.Upd_seigyoAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Upd_seigyoAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Upd_seigyoOperationCompleted == null)) {
                this.Upd_seigyoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpd_seigyoOperationCompleted);
            }
            this.InvokeAsync("Upd_seigyo", new object[] {
                        sUser,
                        sKey}, this.Upd_seigyoOperationCompleted, userState);
        }
        
        private void OnUpd_seigyoOperationCompleted(object arg) {
            if ((this.Upd_seigyoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upd_seigyoCompleted(this, new Upd_seigyoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/login2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] login2(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("login2", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin2(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login2", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] Endlogin2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void login2Async(string[] sUser, string[] sKey) {
            this.login2Async(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void login2Async(string[] sUser, string[] sKey, object userState) {
            if ((this.login2OperationCompleted == null)) {
                this.login2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onlogin2OperationCompleted);
            }
            this.InvokeAsync("login2", new object[] {
                        sUser,
                        sKey}, this.login2OperationCompleted, userState);
        }
        
        private void Onlogin2OperationCompleted(object arg) {
            if ((this.login2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.login2Completed(this, new login2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_tanmatu", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Upd_tanmatu(string[] sUser, string sKey) {
            object[] results = this.Invoke("Upd_tanmatu", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_tanmatu(string[] sUser, string sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_tanmatu", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndUpd_tanmatu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Upd_tanmatuAsync(string[] sUser, string sKey) {
            this.Upd_tanmatuAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Upd_tanmatuAsync(string[] sUser, string sKey, object userState) {
            if ((this.Upd_tanmatuOperationCompleted == null)) {
                this.Upd_tanmatuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpd_tanmatuOperationCompleted);
            }
            this.InvokeAsync("Upd_tanmatu", new object[] {
                        sUser,
                        sKey}, this.Upd_tanmatuOperationCompleted, userState);
        }
        
        private void OnUpd_tanmatuOperationCompleted(object arg) {
            if ((this.Upd_tanmatuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upd_tanmatuCompleted(this, new Upd_tanmatuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB() {
            object[] results = this.Invoke("wakeupDB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wakeupDBAsync() {
            this.wakeupDBAsync(null);
        }
        
        /// <remarks/>
        public void wakeupDBAsync(object userState) {
            if ((this.wakeupDBOperationCompleted == null)) {
                this.wakeupDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwakeupDBOperationCompleted);
            }
            this.InvokeAsync("wakeupDB", new object[0], this.wakeupDBOperationCompleted, userState);
        }
        
        private void OnwakeupDBOperationCompleted(object arg) {
            if ((this.wakeupDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wakeupDBCompleted(this, new wakeupDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Set_tanmatsuCompletedEventHandler(object sender, Set_tanmatsuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_tanmatsuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_tanmatsuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Upd_tanmatsuCompletedEventHandler(object sender, Upd_tanmatsuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upd_tanmatsuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upd_tanmatsuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Upd_riyouCompletedEventHandler(object sender, Upd_riyouCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upd_riyouCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upd_riyouCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_tanmatsu2CompletedEventHandler(object sender, Get_tanmatsu2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_tanmatsu2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_tanmatsu2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_riyouCompletedEventHandler(object sender, Get_riyouCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_riyouCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_riyouCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_seikyuCompletedEventHandler(object sender, Get_seikyuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_seikyuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_seikyuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_jyotaiCompletedEventHandler(object sender, Get_jyotaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_jyotaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_jyotaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_syukabiCompletedEventHandler(object sender, Get_syukabiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_syukabiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_syukabiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_bumonCompletedEventHandler(object sender, Get_bumonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_bumonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_bumonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_messageCompletedEventHandler(object sender, Get_messageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_messageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_messageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_seigyoCompletedEventHandler(object sender, Get_seigyoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_seigyoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_seigyoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Ins_seigyoCompletedEventHandler(object sender, Ins_seigyoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ins_seigyoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ins_seigyoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Upd_seigyoCompletedEventHandler(object sender, Upd_seigyoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upd_seigyoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upd_seigyoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void login2CompletedEventHandler(object sender, login2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class login2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal login2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Upd_tanmatuCompletedEventHandler(object sender, Upd_tanmatuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upd_tanmatuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upd_tanmatuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void wakeupDBCompletedEventHandler(object sender, wakeupDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wakeupDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wakeupDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591